### ISSUE TITLE
Add automated ticket interview

### ISSUE THREAD

**Issue by KarlOfDuty** [KarlOfDuty/SupportBoi#4]
- [x] General config structure.
- [x] Parsing a question from the config into a discord message complete with interaction.
- [x] Logic for identifying where in the interview tree the current conversation is located.
  - Maybe serializing a json copy of the interview which also contains the answers to each question could work. That would get around the issue with updating the config while interviews are in progress. This could however be dangerous for backward-compatibility.
- [x] Saving the interview progress to database.
- [x] Finishing interview with a summary of user responses.
- [x] Command to restart interview.
- [x] Parsing user responses via interactions or replies.

**Comment by docwhomc** [comment]
If the general idea is something like the robot you have to talk to when calling tech support before you get to talk to a person, I've been thinking we need it too. I'd be happy to help code it.

**Comment by KarlOfDuty** [comment]
@docwhomc if you are still interested implementation will begin soon.

**Comment by KarlOfDuty** [comment]
Possible config structure:

```yaml
typequestion:
    message: "Is this ticket a ban appeal?"
    paths:
        - yes:
            message: "What is your user name?"
            conditions: [ equals: "yes", equals: "Yes"  ]
            paths:
                - any:
                    message: "Please write your appeal below."
        - no:
            message: "Please write your issue below."
            conditions: [ notequal: "yes", notequal: "Yes"  ]
```
